### ISSUE TITLE
French Translation 455/737

### ISSUE THREAD

**Issue by MazeWave** [Keksuccino/FancyMenu-Translations#1]
# 455/737\* Lines are currently **translated to French**." #
# 282\* Lines **remaining** to complete. #

Ghostbin : https://ghostbin.com/paste/I4SwI

\*(__empty lines included__)

**Comment by Keksuccino** [comment]
Wow, that's great, thank you very much! If you get it finished, I will add it to the mod!

**Comment by Keksuccino** [comment]
Closed because never finished and outdated now.
